const config = {
  name: 'Will Foster',
  tagline: 'CS + Data Science @ UW–Madison. Building delightful, performant web experiences.',
  subcopy: 'Computer Science & Data Science student focused on ML-backed products, motion, and polished UX.',
  description: 'Will Foster — personal website showcasing projects, experience, and contact.',
  avatar: '/background/Headshot2.png',
  about: 'I’m a CS + DS student at the University of Wisconsin–Madison (’26) from Ann Arbor. I build fast, accessible interfaces and ML‑powered tools that feel crisp and intentional. I love keeping up with new tech and I love sports.',
  aboutHighlights: [
    'Front-end engineering with TypeScript + React',
    'Motion-conscious, accessible UI design',
    'ML integrations and data-driven features',
  ],
  interests: ['Football', 'Basketball', 'Golf', 'Traveling', 'AI'],
  skills: {
    languages: ['Python', 'Java'],
    cloud: ['Azure (Functions, App Services, Cosmos DB)', 'AWS (EC2, Lambda, S3)'],
    other: ['Docker', 'Microservice Architecture', 'RAG'],
  },
  capabilities: ['React', 'TypeScript', 'Tailwind', 'Framer Motion', 'Node', 'Python'],
  contact: {
    email: 'wjfoster2@wisc.edu',
  },
  social: {
    github: 'https://github.com/yourname',
    linkedin: 'https://www.linkedin.com/in/will-foster-551064236/',
  },
  facts: [
    { label: 'University', value: 'UW–Madison' },
    { label: 'Degree', value: 'CS + Data Science' },
    { label: 'Grad', value: 'May 2026' },
    { label: 'Study Abroad', value: 'IFSA Tech Accelerator, Prague' },
  ],
  experience: [
    {
      company: 'Ford Motor Company',
      role: 'Software Engineering Intern',
      period: 'May 2025 — Aug 2025',
      summary: 'Automation tooling and ML-based internal pipelines; reduced repetitive tasks and saved 5000+ hours annually.',
      tech: ['Python', 'ML', 'Automation'],
    },
    {
      company: 'Lawrence AI',
      role: 'Software Engineering Intern',
      period: 'Feb 2025 — May 2025',
      summary: 'RAG pipeline for legal search across 5k+ documents; improved Czech law research speed and accuracy.',
      tech: ['RAG', 'Vector Search', 'LLM'],
    },
    {
      company: 'Quanta (Startup)',
      role: 'Software Engineer Intern',
      period: 'May 2024 — Present',
      summary: 'AI engine and RAG pipeline to extract insights from financial PDFs; accelerated decision-making.',
      tech: ['ETL', 'CI/CD', 'RAG'],
    },
    {
      company: 'ArcTwo',
      role: 'Software Engineer',
      period: 'May 2024 — Sep 2024',
      summary: 'Web-based tool for rapid business model development; front-end, AI coach, and robust back-end.',
      tech: ['React', 'Node', 'AI'],
    },
  ],
  projects: [
    {
      title: 'MadShell (MadHacks)',
      summary: 'Electron CLI emulator with AI natural-language and speech-to-text input; 2nd place overall at MadHacks.',
      description: 'AI-assisted terminal that interprets intent, generates commands, and auto-executes safely.',
      image: '/background/IMG_0180.jpg',
      tags: ['Electron', 'AI', 'Speech'],
      links: { github: '#', live: '#' },
    },
    {
      title: 'Fazah',
      summary: 'AI-powered language learning platform revolutionizing how people acquire new languages.',
      description: 'Innovative language learning platform that uses AI to personalize the learning experience.',
      image: '/background/fazah-logo.png',
      tags: ['AI', 'Education', 'Python'],
      links: { github: '#', live: 'https://pypi.org/project/fazah/' },
    },
    {
      title: 'LungVision',
      summary: 'Advanced AI tool for analyzing lung images, assisting medical professionals in diagnostics.',
      description: 'Deep learning model for automated lung disease detection and classification from medical images.',
      image: '/background/lungvision.png',
      tags: ['AI', 'Healthcare', 'Python'],
      links: { github: 'https://github.com/WillFoster33/Lung-Recognition-Model', live: '#' },
    },
    {
      title: 'Glass UI Kit',
      summary: 'Liquid-glass aesthetics with accessible components and refined motion.',
      description: 'Chips, buttons, and layout primitives designed for clarity and subtle depth.',
      image: '/background/bg2.jpg',
      tags: ['React', 'Tailwind', 'Framer Motion'],
      links: { github: '#', live: '#' },
    },
    {
      title: 'Parallax Playground',
      summary: 'Layered parallax with reduced-motion fallbacks.',
      description: 'Scroll-linked animation experiments with graceful reduction of motion.',
      image: '/background/bg2.jpg',
      tags: ['Scroll', 'Accessibility', 'CSS'],
      links: { github: '#', live: '#' },
    },
    {
      title: 'Portfolio Engine',
      summary: 'Data-driven portfolio templates with MDX and content pipelines.',
      description: 'Headless portfolio engine with theming and content collections.',
      image: '/background/bg2.jpg',
      tags: ['Next.js', 'MDX', 'CMS'],
      links: { github: '#', live: '#' },
    },
    {
      title: 'Motion Recipes',
      summary: 'Micro-interactions and motion patterns for UI polish.',
      description: 'Hover lifts, entrance fades, and modal transitions with accessible patterns.',
      image: '/background/bg2.jpg',
      tags: ['Framer Motion', 'Design'],
      links: { github: '#', live: '#' },
    },
    {
      title: 'Image Lab',
      summary: 'Responsive image utilities and DX for media-heavy sites.',
      description: 'Background helpers, presets, and quality controls for images.',
      image: '/background/bg2.jpg',
      tags: ['Images', 'Performance'],
      links: { github: '#', live: '#' },
    },
  ],
}

export type Project = typeof config.projects[number]
export default config 